source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '9.0'

target 'WJLSDK_Example' do
  
  pod 'AFNetworking',"4.0.1"
  pod 'WJLSDK', :path => '../'

  target 'WJLSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
